Parse Swift operators as link components slightly more strictly
swiftlang/swift-docc pull request #1125
Opened 2024-12-10 10:40 UTC by d-ronnqvist

Bug/issue #, if applicable: 

## Summary

This fixes a very rare and unlikely bug where a Swift operator that contains both a symbol with a diacritic and a forward slash wouldn't parse as a symbol link correctly.

## Dependencies

None.

## Testing

Define a custom `☜⃩/` infix operator and link to it using `☜⃩/(_:_:)`. The link should resolve

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Added tests
- [x] Ran the `./bin/test` script and it succeeded
- [x] ~Updated documentation if necessary~ Not applicable.

2024-12-10 10:49 UTC, d-ronnqvist commented
@swift-ci please test

2024-12-12 01:27 UTC, patshaughnessy requested changes
The code changes look good, and also the new table of unicode values inside of `isValidSwiftOperatorCharacter`.

But can you review the existing unicode values mentioned inside of `isValidSwiftOperatorHead`? The list looks different than what I see in the [Operators discussion on docs.swift.org](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/lexicalstructure/#Operators).

For example, docs.swift.org mentions: 

```
operator-head → U+2190–U+23FF
```

...but I don't see those values in your existing code. Maybe we just need to update the code based on changes to Swift or the Swift docs?

2024-12-12 12:31 UTC, d-ronnqvist commented
@swift-ci please test

2024-12-12 18:30 UTC, patshaughnessy approved these changes

2024-12-12 20:16 UTC, merged